/*
Author Name: Kennedy Seijas
Date: 02/24/2019
Program Name: Seijas_Airplane
Purpose: A calculator to find fibonacci numbers 
         A default Fibonacci number starts from number 1  
         ENTER FIRST NUMBER         : Input from what number you want to start the calculation
         ENTER N TIMES TO CALCULATE : Enter the nth term to generate the Fibonacci sequence and the calculator will provide the Fibonacci sequence up to that nth term.
       
 */
package seijas_fibonacci;

import java.awt.Color;

/**
 *
 * @author Master1
 */
public class Seijas_CalculateFibonacciNumbers extends javax.swing.JFrame {

    /**
     * Creates new form Seijas_CalculateFibonacciNumbers
     */
    public Seijas_CalculateFibonacciNumbers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelFirstNumber = new javax.swing.JLabel();
        jTextFieldNumber1 = new javax.swing.JTextField();
        jLabelTimeCalculation = new javax.swing.JLabel();
        jTextFieldNTimes = new javax.swing.JTextField();
        jButtonCalculate = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaFibonacciNumbers = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabelFiboCalculated = new javax.swing.JLabel();
        jLabelTOTALFibo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonClear = new javax.swing.JButton();
        jButtonRecursive = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTitle.setText("Calculate Fibonacci Numbers");

        jLabelFirstNumber.setText("Enter the First Number to start to calculate");

        jTextFieldNumber1.setText("1");
        jTextFieldNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumber1ActionPerformed(evt);
            }
        });

        jLabelTimeCalculation.setText("Enter the value for Nth Term to calculate");

        jTextFieldNTimes.setText("1");
        jTextFieldNTimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNTimesActionPerformed(evt);
            }
        });

        jButtonCalculate.setText("Calculate Iterative");
        jButtonCalculate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCalculateMouseClicked(evt);
            }
        });

        jButtonClose.setText("Close");
        jButtonClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCloseMouseClicked(evt);
            }
        });

        jTextAreaFibonacciNumbers.setColumns(20);
        jTextAreaFibonacciNumbers.setForeground(new java.awt.Color(51, 51, 255));
        jTextAreaFibonacciNumbers.setRows(5);
        jScrollPane1.setViewportView(jTextAreaFibonacciNumbers);

        jLabelFiboCalculated.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelFiboCalculated.setText("The Sum of Fibonacci Calculated");

        jLabelTOTALFibo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelTOTALFibo.setForeground(new java.awt.Color(0, 153, 255));
        jLabelTOTALFibo.setText("0");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Fibonacci Serie");

        jLabel3.setText("Created by Kennedy Seijas");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jLabel4.setText("CEN3024: Software Development I (Online) 12949");

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel5.setText("Enter the nth term to generate the Fibonacci sequence and the calculator will provide the Fibonacci sequence up to that nth term.");

        jButtonClear.setText("Clear");
        jButtonClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClearMouseClicked(evt);
            }
        });

        jButtonRecursive.setText("Calculate Recursive");
        jButtonRecursive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRecursiveMouseClicked(evt);
            }
        });
        jButtonRecursive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecursiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonRecursive)
                        .addGap(32, 32, 32)
                        .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabelTitle))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCalculate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabelTimeCalculation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldNTimes, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabelFirstNumber)
                                .addGap(66, 66, 66)
                                .addComponent(jTextFieldNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelTOTALFibo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelFiboCalculated)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFirstNumber)
                            .addComponent(jTextFieldNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTimeCalculation)
                            .addComponent(jTextFieldNTimes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelFiboCalculated)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTOTALFibo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCalculate)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonRecursive)
                        .addComponent(jButtonClear)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonClose, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabelTimeCalculation.getAccessibleContext().setAccessibleName("nCalculation");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumber1ActionPerformed

    private void jButtonCalculateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCalculateMouseClicked
        // TODO add your handling code here:
        // Calculate the numbers and display them into the Text Area
        String x = " ", nFirstNumber,nTimes;
        nFirstNumber = this.jTextFieldNumber1.getText();
        nTimes       = this.jTextFieldNTimes.getText();
        jTextAreaFibonacciNumbers.setText("0");               
                
        x = Calculate_Fibonacci(nFirstNumber, nTimes);
        jTextAreaFibonacciNumbers.setForeground(Color.blue);
        jTextAreaFibonacciNumbers.setText(x);
    }//GEN-LAST:event_jButtonCalculateMouseClicked

    private void jButtonCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonCloseMouseClicked

    private void jButtonClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClearMouseClicked
        // Clear all input data
        jTextAreaFibonacciNumbers.setText("");
        jTextFieldNTimes.setText("1");
        jTextFieldNumber1.setText("1");
        jLabelTOTALFibo.setText("0");
        
        
        
    }//GEN-LAST:event_jButtonClearMouseClicked

    private void jButtonRecursiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecursiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRecursiveActionPerformed

    private void jButtonRecursiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRecursiveMouseClicked
        // A math formula to calculate the fibonacci
        int x = 0; String nTimes;
        nTimes       = this.jTextFieldNTimes.getText();
        nLoops = 0;
        jTextAreaFibonacciNumbers.setForeground(Color.red);
        nTotalFibonacciRe= 1;
        jTextAreaFibonacciNumbers.setText("0, 1, "); // clean calculated fibonacci box
        
        nMaxLoops = Integer.parseInt(nTimes); // max loops to be calculated
        x= fibonacciRecursive(0,1); // Calculate Fibonacci
        jLabelTOTALFibo.setText(Integer.toString(nTotalFibonacciRe));        
    }//GEN-LAST:event_jButtonRecursiveMouseClicked

    private void jTextFieldNTimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNTimesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNTimesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seijas_CalculateFibonacciNumbers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seijas_CalculateFibonacciNumbers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seijas_CalculateFibonacciNumbers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seijas_CalculateFibonacciNumbers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seijas_CalculateFibonacciNumbers().setVisible(true);
            }
        });
    }
    
    /*
    String Number1 : An String field with the starting number for calculing
    String nTimes  : Number of terms to be calculated
    */
    
    public String Calculate_Fibonacci(String Number1, String sTimes){
     String x = ""; // String with calculated Fibonacci numbers
     String sCalculated = "";
     int nEndline = 1; // Add an Enter every nEndLine calculations
     int nTotalFibonacci = 1; // the calculated Number
     int nStart = Integer.parseInt(Number1);
     int nTimes = Integer.parseInt(sTimes);
     
     int n1= 0;
     int n2= 1;
     int n3 = 1;
                  
     int count = nTimes + nStart - 2; // Number of times the 
                                                        //number will be calculated
     int i=0;
     
     final long startTime = System.nanoTime();     
     if (nStart <=1) x= "0, 1"; // DEfault Fibonacci of 1
     
     
             //System.out.print(n1+" "+n2);//printing 0 and 1    
            for(i=0;i<count;++i)//loop starts from 2 because 0 and 1 are already printed    
            {    
                n3=n1+n2;     
                
                nTotalFibonacci = nTotalFibonacci+n3;     
                sCalculated = Integer.toString(nTotalFibonacci);
                
                jLabelTOTALFibo.setText(sCalculated); // Display the calculated Fibonacci
                
                 // Only with stetic proposes, it display the number from the desired number
                if (n3>=nStart) x+= ", " + n3 ;                  
                
                
                if (nEndline ==10) { // Add Enter every 10 numbers
                    x+= "\n";
                    nEndline = 0;
                }
                nEndline ++;
                
                n1=n2;    
                n2=n3;    
                
            } 
           
            final long duration = System.nanoTime() - startTime; 
            System.out.println("***** ITERATIVE FIBONACCI time enlapsed: "+ duration);
         
         return x;   
    }
    


/**
	 * Recursive implementation for nth fibonacci number
	 * Time complexity - O(n)
	 * Space complexity - O(n)
	 * 
	 * @param n
	 * @return
	 */
	public int fibonacciRecursive(int n1, int n2) {
         // int n = Integer.parseInt(sTimes), n3;
         int n3= 0;
         String x; 
         
         String sCalculated = "";
         final long startTime = System.nanoTime();
         
         nLoops += 1 ;
         
		if(nLoops == nMaxLoops ) {
			return n3;
		}
                
                sCalculated = Integer.toString(n1+n2);
                n3 = n1+n2;
                // Sum The calculated numbers
                nTotalFibonacciRe += n3; // Total Calculated Fibonacci 
                
                                                        
                final long duration = System.nanoTime() - startTime;
                
                System.out.println("RECURSIVE FIBONACCI time enlapsed: "+ duration);
                        
		// Add the calculated number to the box
                x = jTextAreaFibonacciNumbers.getText();
                jTextAreaFibonacciNumbers.setText(x+ sCalculated + ", " );
                return fibonacciRecursive(n2, n3 );
	}    
    public int nLoops = 1; // Times the recursive will loop
    public int nMaxLoops = 0; // the MAx recursive loops
    public int nTotalFibonacciRe =1;   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalculate;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonRecursive;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelFiboCalculated;
    private javax.swing.JLabel jLabelFirstNumber;
    public static javax.swing.JLabel jLabelTOTALFibo;
    private javax.swing.JLabel jLabelTimeCalculation;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea jTextAreaFibonacciNumbers;
    public static javax.swing.JTextField jTextFieldNTimes;
    public static javax.swing.JTextField jTextFieldNumber1;
    // End of variables declaration//GEN-END:variables
    


}
